### ISSUE TITLE
Build error on CentOS 5

### ISSUE THREAD

**Issue by johanneskoester** [GATB/bcalm#7]
Dear authors,
I tried to build bcalm on CentOS 5 in order to package it for [Bioconda](https://bioconda.github.io). Unfortunately, I get an error that I can't easily solve (see [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/144154593/log.txt)). Please apologize for the logging around the true build output. This comes from our CI system.

Best,
Johannes

**Comment by rchikhi** [comment]
Hi Johannes,
Apologies for the delay. I don't exactly know how to solve the compilation problem that you're showing. However I've been able to build bcalm using travis and two different compilers, see the following file: https://github.com/GATB/bcalm/blob/master/.travis.yml
Could perhaps these travis settings be somehow used in order to build the bioconda package?

**Comment by johanneskoester** [comment]
We will switch to CentOS 6 soon. That should make it work! Thanks.
